/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StudentController;
import model.StudentModel;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;

/**
 *
 * @author KPES
 */
public class StudentView extends javax.swing.JFrame {
    
    //global variables
    private final StudentController sc;
    
    
    /**
     * Creates new form EmployeeView
     */
    public StudentView() {
        this.sc =  new StudentController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JTabbedPane();
        addPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        cbYearLevel = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();
        cbProgram = new javax.swing.JComboBox<>();
        txtStudentNo = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        spnrAge = new javax.swing.JSpinner();
        searchPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSearchSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearchSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRes = new javax.swing.JList<>();
        btnClearSearch = new javax.swing.JButton();
        viewPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbViewOptView = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtSearchView = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnSearchView = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtFirstNameView = new javax.swing.JLabel();
        txtYearlLevelView = new javax.swing.JLabel();
        txtGenderView = new javax.swing.JLabel();
        txtLastNameView = new javax.swing.JLabel();
        txtAgeView = new javax.swing.JLabel();
        txtProgramView = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtStudentNoView = new javax.swing.JLabel();
        btnClearView = new javax.swing.JButton();
        updatePane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbViewOptUpd = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtSearchUpd = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFirstNameUpd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLastNameUpd = new javax.swing.JTextField();
        cbYearLevelUpd = new javax.swing.JComboBox<>();
        cbGenderUpd = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbProgramUpd = new javax.swing.JComboBox<>();
        txtStudentNoUpd = new javax.swing.JLabel();
        btnSearchUpd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        spnrAgeUpd = new javax.swing.JSpinner();
        btnClearUpd = new javax.swing.JButton();
        deletePane = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        cbViewOptDel = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        txtSearchDel = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        btnSearchDel = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtFirstNameDel = new javax.swing.JLabel();
        txtYearLevelDel = new javax.swing.JLabel();
        txtGenderDel = new javax.swing.JLabel();
        txtLastNameDel = new javax.swing.JLabel();
        txtAgeDel = new javax.swing.JLabel();
        txtProgramDel = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtStudentNoDel = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClearDel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIP Student Record");
        setPreferredSize(new java.awt.Dimension(650, 400));
        setResizable(false);

        jLabel1.setText("Student no.");

        jLabel2.setText("First name");

        jLabel3.setText("Last name");

        jLabel4.setText("Year level");

        jLabel5.setText("Age");

        jLabel6.setText("Gender");

        jLabel7.setText("Program");

        cbYearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Non-binary" }));

        cbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSCS", "BSIS", "BSIT", "BSEMC", "BSArch", "BSChemE", "BSCE", "BSCpE", "BSEE", "BSIE", "BSME", "BSA" }));

        txtStudentNo.setText("2022-"+String.valueOf(sc.getCurrentID()));
        txtStudentNo.setToolTipText("\"Student Number\"");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        spnrAge.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout addPaneLayout = new javax.swing.GroupLayout(addPane);
        addPane.setLayout(addPaneLayout);
        addPaneLayout.setHorizontalGroup(
            addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStudentNo))
                    .addGroup(addPaneLayout.createSequentialGroup()
                        .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaneLayout.createSequentialGroup()
                                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18))
                            .addGroup(addPaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)))
                        .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbYearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spnrAge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbProgram, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnAdd))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        addPaneLayout.setVerticalGroup(
            addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentNo))
                .addGap(18, 18, 18)
                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbYearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnrAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAdd)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        mainPane.addTab("Add Student", addPane);

        jLabel8.setText("Name");

        btnSearchSearch.setText("Search");
        btnSearchSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSearchActionPerformed(evt);
            }
        });

        jLabel9.setText("Results");

        listRes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listRes);

        btnClearSearch.setText("Clear");
        btnClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchSearch)
                        .addGap(51, 51, 51))
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClearSearch)
                            .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSearchSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearSearch)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPane.addTab("Search Student", searchPane);

        jLabel10.setText("View by");

        cbViewOptView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student no.", "Last name" }));

        jLabel11.setText("Last name/Student no.");

        jLabel12.setText("Student details");

        btnSearchView.setText("Search");
        btnSearchView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchViewActionPerformed(evt);
            }
        });

        jLabel23.setText("First name");

        jLabel24.setText("Year level");

        jLabel25.setText("Gender");

        jLabel26.setText("Last name");

        jLabel27.setText("Age");

        jLabel28.setText("Program");

        txtFirstNameView.setText("----------");

        txtYearlLevelView.setText("----------");

        txtGenderView.setText("----------");

        txtLastNameView.setText("----------");

        txtAgeView.setText("----------");

        txtProgramView.setText("----------");

        jLabel35.setText("Student no.");

        txtStudentNoView.setText("2022-");

        btnClearView.setText("Clear");
        btnClearView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPaneLayout = new javax.swing.GroupLayout(viewPane);
        viewPane.setLayout(viewPaneLayout);
        viewPaneLayout.setHorizontalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPaneLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentNoView))
                    .addGroup(viewPaneLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbViewOptView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchView, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchView))
                    .addComponent(jLabel12)
                    .addGroup(viewPaneLayout.createSequentialGroup()
                        .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewPaneLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtFirstNameView))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYearlLevelView, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGenderView, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(123, 123, 123)
                        .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewPaneLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProgramView))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPaneLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgeView))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPaneLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastNameView)))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearView)
                .addGap(34, 34, 34))
        );
        viewPaneLayout.setVerticalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbViewOptView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtSearchView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(19, 19, 19)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtStudentNoView))
                .addGap(18, 18, 18)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(txtFirstNameView)
                    .addComponent(txtLastNameView))
                .addGap(18, 18, 18)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(txtYearlLevelView)
                    .addComponent(txtAgeView))
                .addGap(18, 18, 18)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(txtGenderView)
                    .addComponent(txtProgramView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearView)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainPane.addTab("View Student", viewPane);

        jLabel13.setText("Search by");

        cbViewOptUpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student no.", "Last name" }));

        jLabel14.setText("Last name/Student no.");

        jLabel15.setText("Student no.");

        jLabel16.setText("First name");

        jLabel17.setText("Year level");

        jLabel18.setText("Gender");

        txtFirstNameUpd.setEditable(false);

        jLabel19.setText("Last name");

        txtLastNameUpd.setEditable(false);

        cbYearLevelUpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cbGenderUpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Non-binary" }));

        jLabel20.setText("Age");

        jLabel21.setText("Program");

        cbProgramUpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSCS", "BSIS", "BSIT", "BSEMC", "BSArch", "BSChemE", "BSCE", "BSCpE", "BSEE", "BSIE", "BSME", "BSA" }));

        txtStudentNoUpd.setText("2022-");

        btnSearchUpd.setText("Search");
        btnSearchUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUpdActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        spnrAgeUpd.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnClearUpd.setText("Clear");
        btnClearUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUpdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePaneLayout = new javax.swing.GroupLayout(updatePane);
        updatePane.setLayout(updatePaneLayout);
        updatePaneLayout.setHorizontalGroup(
            updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(updatePaneLayout.createSequentialGroup()
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbViewOptUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnSearchUpd))
                    .addGroup(updatePaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePaneLayout.createSequentialGroup()
                                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15))
                                .addGap(30, 30, 30)
                                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatePaneLayout.createSequentialGroup()
                                        .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbYearLevelUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGenderUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFirstNameUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePaneLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtLastNameUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(updatePaneLayout.createSequentialGroup()
                                                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbProgramUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spnrAgeUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(90, 90, 90))))
                                    .addComponent(txtStudentNoUpd)))
                            .addComponent(btnClearUpd))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(22, 22, 22))
        );
        updatePaneLayout.setVerticalGroup(
            updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbViewOptUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtSearchUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnSearchUpd))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtStudentNoUpd))
                .addGap(18, 18, 18)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtFirstNameUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtLastNameUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbYearLevelUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(spnrAgeUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbGenderUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cbProgramUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnClearUpd))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPane.addTab("Update Student", updatePane);

        jLabel37.setText("Search by");

        cbViewOptDel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student no.", "Last name" }));

        jLabel38.setText("Last name/Student no.");

        jLabel39.setText("Student details");

        btnSearchDel.setText("Search");
        btnSearchDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDelActionPerformed(evt);
            }
        });

        jLabel40.setText("First name");

        jLabel41.setText("Year level");

        jLabel42.setText("Gender");

        jLabel43.setText("Last name");

        jLabel44.setText("Age");

        jLabel45.setText("Program");

        txtFirstNameDel.setText("----------");

        txtYearLevelDel.setText("----------");

        txtGenderDel.setText("----------");

        txtLastNameDel.setText("----------");

        txtAgeDel.setText("----------");

        txtProgramDel.setText("----------");

        jLabel52.setText("Student no.");

        txtStudentNoDel.setText("2022-");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClearDel.setText("Clear");
        btnClearDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePaneLayout = new javax.swing.GroupLayout(deletePane);
        deletePane.setLayout(deletePaneLayout);
        deletePaneLayout.setHorizontalGroup(
            deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(deletePaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePaneLayout.createSequentialGroup()
                        .addComponent(btnClearDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(38, 38, 38))
                    .addGroup(deletePaneLayout.createSequentialGroup()
                        .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deletePaneLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentNoDel))
                            .addGroup(deletePaneLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbViewOptDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchDel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchDel))
                            .addComponent(jLabel39)
                            .addGroup(deletePaneLayout.createSequentialGroup()
                                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42))
                                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deletePaneLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(txtFirstNameDel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePaneLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtYearLevelDel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtGenderDel, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(123, 123, 123)
                                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(deletePaneLayout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtProgramDel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePaneLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAgeDel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePaneLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastNameDel)))))
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        deletePaneLayout.setVerticalGroup(
            deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbViewOptDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(txtSearchDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(19, 19, 19)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txtStudentNoDel))
                .addGap(18, 18, 18)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel43)
                    .addComponent(txtFirstNameDel)
                    .addComponent(txtLastNameDel))
                .addGap(18, 18, 18)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel44)
                    .addComponent(txtYearLevelDel)
                    .addComponent(txtAgeDel))
                .addGap(18, 18, 18)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel45)
                    .addComponent(txtGenderDel)
                    .addComponent(txtProgramDel))
                .addGap(18, 18, 18)
                .addGroup(deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClearDel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        mainPane.addTab("Delete Student", deletePane);

        jMenu1.setText("File");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int studentNo = Integer.parseInt(Arrays.asList(txtStudentNo.getText().split("-")).get(1)); // Separate 2022 from id value
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int yearLevel = Integer.parseInt(cbYearLevel.getSelectedItem().toString());
        int age = (Integer) spnrAge.getValue();
        String gender = cbGender.getSelectedItem().toString();
        String program = cbProgram.getSelectedItem().toString();
        
        String errors = "";
        if (firstName.length() == 0) {
            errors += " - firstName\n";
        }
        
        if (lastName.length() == 0) {
            errors += " - lastName\n";
        }
        
        if (age < 0) {
            errors += " - age\n";
        }
        
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(null, errors, "Invalid fields", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        StudentModel student = new StudentModel(studentNo, firstName, lastName, yearLevel, age, gender, program);
        sc.incrementID();
        sc.createStudent(student);
        // Reload view
        sc.loadData();
        txtStudentNo.setText("2022-"+String.valueOf(sc.getCurrentID()));
        // Clear first name and last name, other fields can be reused
        txtFirstName.setText("");
        txtLastName.setText("");
        JOptionPane.showMessageDialog(this, "Student successfully added", "Add", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSearchActionPerformed
        String input = txtSearchSearch.getText();
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(null, "Search box empty", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<String> result = sc.searchRegex(input);
            DefaultListModel listModel = new DefaultListModel();
            if(result.isEmpty()){
                listModel.addElement("NO RESULT");
            } else {
                listModel.addAll(result);
            }
            listRes.setModel(listModel);
        }
                   
    }//GEN-LAST:event_btnSearchSearchActionPerformed

    private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSearchActionPerformed
        listRes.setModel(new DefaultListModel());
    }//GEN-LAST:event_btnClearSearchActionPerformed

    private void btnSearchViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchViewActionPerformed
        int searchComp = 0;
        String opt = cbViewOptView.getSelectedItem().toString();
        String query = txtSearchView.getText();
        String[] result = new String[7];
        
        if (opt.equals("Student no.")){
            // For Input Validation
             Pattern pattern = Pattern.compile("2022-\\d+");
             Matcher m = pattern.matcher(query);
             
             if(m.matches()){
                 String[] revQuery = query.split("-"); //2022-#             
                 result = sc.searchStudent(opt, revQuery[1]);
                 searchComp = 1;
             } else {
                 JOptionPane.showMessageDialog(null, "Invalid student number", "Input Error", JOptionPane.ERROR_MESSAGE);
             }
             
        } else {
            result = sc.searchStudent(opt, query);
            searchComp = 1;
        }
       
       if(result[0] == null && searchComp == 1){
           JOptionPane.showMessageDialog(null, "No Result", "Search Result", JOptionPane.INFORMATION_MESSAGE);
           txtStudentNoView.setText("2022-");
           txtFirstNameView.setText("----------");
           txtLastNameView.setText("----------");
           txtYearlLevelView.setText("----------");
           txtAgeView.setText("----------");
           txtGenderView.setText("----------");
           txtProgramView.setText("----------");
       } else if (searchComp == 1){
           txtStudentNoView.setText("2022-"+result[0]);
           txtFirstNameView.setText(result[1]);
           txtLastNameView.setText(result[2]);
           txtYearlLevelView.setText(result[3]);
           txtAgeView.setText(result[4]);
           txtGenderView.setText(result[5]);
           txtProgramView.setText(result[6]);
       }      
    }//GEN-LAST:event_btnSearchViewActionPerformed

    private void btnClearViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearViewActionPerformed
        txtStudentNoView.setText("2022-");
        txtFirstNameView.setText("----------");
        txtLastNameView.setText("----------");
        txtYearlLevelView.setText("----------");
        txtAgeView.setText("----------");
        txtGenderView.setText("----------");
        txtProgramView.setText("----------");
        txtSearchView.setText("");
    }//GEN-LAST:event_btnClearViewActionPerformed

    private void btnSearchUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUpdActionPerformed
        int searchComp = 0;
        String opt = cbViewOptUpd.getSelectedItem().toString();
        String query = txtSearchUpd.getText();
        String[] result = new String[7];
        
        if (opt.equals("Student no.")){
            // For Input Validation
             Pattern pattern = Pattern.compile("2022-\\d+");
             Matcher m = pattern.matcher(query);
             
             if(m.matches()){
                 String[] revQuery = query.split("-"); //2022-#             
                 result = sc.searchStudent(opt, revQuery[1]);
                 searchComp = 1;
             } else {
                 JOptionPane.showMessageDialog(null, "Invalid student number", "Input Error", JOptionPane.ERROR_MESSAGE);
             }
             
        } else {
            result = sc.searchStudent(opt, query);
            searchComp = 1;
        }
        if(result[0] == null && searchComp == 1){
           JOptionPane.showMessageDialog(null, "No Result", "Search Result", JOptionPane.INFORMATION_MESSAGE);
           txtStudentNoUpd.setText("2022-");
           txtFirstNameUpd.setText("");
           txtLastNameUpd.setText("");
           cbYearLevelUpd.setSelectedIndex(0);
           spnrAgeUpd.setValue(0);
           cbGenderUpd.setSelectedIndex(0);
           cbProgramUpd.setSelectedIndex(0);
        } else if (searchComp == 1){
           txtStudentNoUpd.setText("2022-"+result[0]);
           txtFirstNameUpd.setText(result[1]);
           txtLastNameUpd.setText(result[2]);
           cbYearLevelUpd.setSelectedItem(result[3]);
           int age = Integer.parseInt(result[4]);
           spnrAgeUpd.setValue(age);
           cbGenderUpd.setSelectedItem(result[5]);
           cbProgramUpd.setSelectedItem(result[6]);
           txtFirstNameUpd.setEditable(true);
           txtLastNameUpd.setEditable(true);
        }
    }//GEN-LAST:event_btnSearchUpdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(txtFirstNameUpd.getText().isEmpty() || txtLastNameUpd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No student selected / Fields cannot be empty", "Input error", JOptionPane.ERROR_MESSAGE);
        } else {
           int studentNo = Integer.parseInt(Arrays.asList(txtStudentNoUpd.getText().split("-")).get(1));
           String firstName = txtFirstNameUpd.getText();
           String lastName = txtLastNameUpd.getText();
           int yearLevel = Integer.parseInt(cbYearLevelUpd.getSelectedItem().toString());
           int age = (Integer)spnrAgeUpd.getValue();
           String gender = cbGenderUpd.getSelectedItem().toString();
           String program = cbProgramUpd.getSelectedItem().toString();
           
           if(sc.updateStudent(studentNo, firstName, lastName, yearLevel, age, gender, program)){
                JOptionPane.showMessageDialog(null, "Update Successful", "Update", JOptionPane.INFORMATION_MESSAGE);
                sc.loadData();
                txtStudentNoUpd.setText("2022-");
                txtFirstNameUpd.setText("");
                txtLastNameUpd.setText("");
                cbYearLevelUpd.setSelectedIndex(0);
                spnrAgeUpd.setValue(0);
                cbGenderUpd.setSelectedIndex(0);
                cbProgramUpd.setSelectedIndex(0);
                txtFirstNameUpd.setEditable(false);
                txtLastNameUpd.setEditable(false);
           } else {
               JOptionPane.showMessageDialog(null, "Update Failed", "Update", JOptionPane.ERROR_MESSAGE);
           }
           
        }        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Application",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        String aboutMsg = "<html>"
                + "CCS 203-CS21FA1 Final Project<br>"
                + "Created by:<br>"
                + "<font style=\"font-weight: bold;\">HIJE</font>, Jericho<br>"
                + "<font style=\"font-weight: bold;\">MARTINEZ</font>, Sebastian Gabriel E.<br>"
                + "<font style=\"font-weight: bold;\">SANTILLAN</font>, Krizzia Pearl E.<br>"
                + "<font style=\"font-weight: bold;\">PAULINO</font>, Selwyn<br><br>"
                + "<p>"
                + "A simple application for managing student information.<br><br>"
                + "For educational purposes only."
                + "</p>"
                + "</html>";
        JOptionPane.showMessageDialog(this, aboutMsg, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void btnSearchDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDelActionPerformed
        int searchComp = 0;
        String opt = cbViewOptDel.getSelectedItem().toString();
        String query = txtSearchDel.getText();
        String[] result = new String[7];
        
        if (opt.equals("Student no.")){
            // For Input Validation
             Pattern pattern = Pattern.compile("2022-\\d+");
             Matcher m = pattern.matcher(query);
             
            if(m.matches()){
                String[] revQuery = query.split("-"); //2022-#             
                result = sc.searchStudent(opt, revQuery[1]);
                searchComp = 1;
            } else {
                JOptionPane.showMessageDialog(null, "Invalid student number", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtStudentNoDel.setText("2022-");
                txtFirstNameDel.setText("----------");
                txtLastNameDel.setText("----------");
                txtYearLevelDel.setText("----------");
                txtAgeDel.setText("----------");
                txtGenderDel.setText("----------");
                txtProgramDel.setText("----------");
            }
             
        } else {
            result = sc.searchStudent(opt, query);
            searchComp = 1;
        }
        if(result[0] == null && searchComp == 1){
            JOptionPane.showMessageDialog(null, "No Result", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            txtStudentNoDel.setText("2022-");
            txtFirstNameDel.setText("----------");
            txtLastNameDel.setText("----------");
            txtYearLevelDel.setText("----------");
            txtAgeDel.setText("----------");
            txtGenderDel.setText("----------");
            txtProgramDel.setText("----------");
        } else if (searchComp == 1){
            txtStudentNoDel.setText("2022-"+result[0]);
            txtFirstNameDel.setText(result[1]);
            txtLastNameDel.setText(result[2]);
            txtYearLevelDel.setText(result[3]);
            txtAgeDel.setText(result[4]);
            txtGenderDel.setText(result[5]);
            txtProgramDel.setText(result[6]);
        }
    }//GEN-LAST:event_btnSearchDelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(txtFirstNameDel.getText().equals("----------") || txtLastNameDel.getText().equals("----------")){
            JOptionPane.showMessageDialog(null, "No student selected", "Input error", JOptionPane.ERROR_MESSAGE);
	} else {
            int confirm = JOptionPane.showConfirmDialog(null, "Confirm deletion?");
            if(confirm == 0){
                int studentNo = Integer.parseInt(Arrays.asList(txtStudentNoDel.getText().split("-")).get(1));
                if (sc.deleteStudent(studentNo)){
                    JOptionPane.showMessageDialog(null, "Deleted Student Record", "Update", JOptionPane.INFORMATION_MESSAGE);
                    txtStudentNoDel.setText("2022-");
                    txtFirstNameDel.setText("----------");
                    txtLastNameDel.setText("----------");
                    txtYearLevelDel.setText("----------");
                    txtAgeDel.setText("----------");
                    txtGenderDel.setText("----------");
                    txtProgramDel.setText("----------");
                    sc.loadData();
                } else {
                    JOptionPane.showMessageDialog(null, "An error occurred. Operation failed", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(null, "Retained student record", "Update", JOptionPane.INFORMATION_MESSAGE);
                txtStudentNoDel.setText("2022-");
                txtFirstNameDel.setText("----------");
                txtLastNameDel.setText("----------");
                txtYearLevelDel.setText("----------");
                txtAgeDel.setText("----------");
                txtGenderDel.setText("----------");
                txtProgramDel.setText("----------");                
            }
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUpdActionPerformed
        txtStudentNoUpd.setText("2022-");
        txtFirstNameUpd.setText("");
        txtLastNameUpd.setText("");
        cbYearLevelUpd.setSelectedIndex(0);
        spnrAgeUpd.setValue(0);
        cbGenderUpd.setSelectedIndex(0);
        cbProgramUpd.setSelectedIndex(0);
        txtFirstNameUpd.setEditable(false);
        txtLastNameUpd.setEditable(false);
    }//GEN-LAST:event_btnClearUpdActionPerformed

    private void btnClearDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDelActionPerformed
        txtStudentNoDel.setText("2022-");
        txtFirstNameDel.setText("----------");
        txtLastNameDel.setText("----------");
        txtYearLevelDel.setText("----------");
        txtAgeDel.setText("----------");
        txtGenderDel.setText("----------");
        txtProgramDel.setText("----------"); 
    }//GEN-LAST:event_btnClearDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPane;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearDel;
    private javax.swing.JButton btnClearSearch;
    private javax.swing.JButton btnClearUpd;
    private javax.swing.JButton btnClearView;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchDel;
    private javax.swing.JButton btnSearchSearch;
    private javax.swing.JButton btnSearchUpd;
    private javax.swing.JButton btnSearchView;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbGenderUpd;
    private javax.swing.JComboBox<String> cbProgram;
    private javax.swing.JComboBox<String> cbProgramUpd;
    private javax.swing.JComboBox<String> cbViewOptDel;
    private javax.swing.JComboBox<String> cbViewOptUpd;
    private javax.swing.JComboBox<String> cbViewOptView;
    private javax.swing.JComboBox<String> cbYearLevel;
    private javax.swing.JComboBox<String> cbYearLevelUpd;
    private javax.swing.JPanel deletePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JList<String> listRes;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JPanel searchPane;
    private javax.swing.JSpinner spnrAge;
    private javax.swing.JSpinner spnrAgeUpd;
    private javax.swing.JLabel txtAgeDel;
    private javax.swing.JLabel txtAgeView;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JLabel txtFirstNameDel;
    private javax.swing.JTextField txtFirstNameUpd;
    private javax.swing.JLabel txtFirstNameView;
    private javax.swing.JLabel txtGenderDel;
    private javax.swing.JLabel txtGenderView;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JLabel txtLastNameDel;
    private javax.swing.JTextField txtLastNameUpd;
    private javax.swing.JLabel txtLastNameView;
    private javax.swing.JLabel txtProgramDel;
    private javax.swing.JLabel txtProgramView;
    private javax.swing.JTextField txtSearchDel;
    private javax.swing.JTextField txtSearchSearch;
    private javax.swing.JTextField txtSearchUpd;
    private javax.swing.JTextField txtSearchView;
    private javax.swing.JLabel txtStudentNo;
    private javax.swing.JLabel txtStudentNoDel;
    private javax.swing.JLabel txtStudentNoUpd;
    private javax.swing.JLabel txtStudentNoView;
    private javax.swing.JLabel txtYearLevelDel;
    private javax.swing.JLabel txtYearlLevelView;
    private javax.swing.JPanel updatePane;
    private javax.swing.JPanel viewPane;
    // End of variables declaration//GEN-END:variables
}
